### ISSUE TITLE
ppc64le

### ISSUE THREAD

**Issue by sdarwin** [jeking3/bdde#3]
Hi @jeking3,

There is some interest from boostorg/math to include tests for the ppc64le architecture. In the README file, it mentions "Supported combinations of architecture and OS:"  Could ppc64le be added?

**Comment by jeking3** [comment]
Hi, yes, I think it could be.

**Comment by jeking3** [comment]
I assume ubuntu focal ppc64el would be sufficient for this?

**Comment by sdarwin** [comment]
The most recent LTS Releases of Ubuntu:

[Ubuntu 24.04 LTS (Noble Numbat) ›](https://releases.ubuntu.com/noble/)
[Ubuntu 22.04.4 LTS (Jammy Jellyfish) ›](https://releases.ubuntu.com/jammy/)
[Ubuntu 20.04.6 LTS (Focal Fossa) ›](https://releases.ubuntu.com/focal/)

my general strategy about versions is to prefer the newest recent release, unless something is blocking that.     It offers the longest runway, before upgrading again is necessary.  

1st choice, Ubuntu 24.04 Noble Numbat.
2nd choice, Ubuntu 22.04 Jammy.

**Comment by jeking3** [comment]
I there an alpine release you would prefer?  The ubuntu and fedora multiarch containers are not being kept up to date that well.

**Comment by sdarwin** [comment]
- Packages installation is more standard on ubuntu.  Most boost-ci scripts use ubuntu. Is multiarch support not available?

- The original request came from boostorg/math and Matt Borland. I think you were chatting with him. If he believes alpine is acceptable, try it out.

**Comment by jeking3** [comment]
This will be in v3.0.0

**Comment by jeking3** [comment]
v3.0.0 published and includes ppc64le/el images
